/**
 * Pure generator for the `superstyling.d.ts` file. Kept free of IO so it can
 * be unit-tested and reused programmatically (e.g., by build plugins).
 *
 * See PLAN.md Q18: users augment Tamagui's `TamaguiCustomConfig` with their
 * Superstyling system config to get typed tokens, shortcuts, and themes in
 * style props without deep generics.
 */

export interface GenerateOptions {
  /**
   * Import path to the user's system file (the one that exports a `createSystem`
   * result). When omitted, the generated file uses `@superstyling/core`'s
   * `defaultSystem` so the zero-config path is still typed.
   */
  systemImport?: string;
  /**
   * Name of the exported system symbol in that module. Default: `"system"`.
   */
  systemExportName?: string;
}

/**
 * Returns the full contents of the `.d.ts` file to write.
 * Does not touch the filesystem.
 */
export function generateTypeDeclaration(options: GenerateOptions = {}): string {
  const { systemImport, systemExportName = "system" } = options;
  const header = buildHeader();
  const body = systemImport
    ? buildUserSystemBody(systemImport, systemExportName)
    : buildDefaultSystemBody();
  return `${header}\n${body}\n`;
}

function buildHeader(): string {
  return [
    "// Auto-generated by `superstyling init-types`.",
    "// Do not edit by hand — rerun the CLI after changing your system config.",
    "//",
    "// This file teaches Tamagui's TypeScript types about your Superstyling",
    '// system so that style props (e.g., `bg="blue.500"`), shortcuts,',
    "// semantic tokens, and colorScheme themes autocomplete correctly.",
  ].join("\n");
}

function buildDefaultSystemBody(): string {
  return [
    'import type { defaultSystem } from "@superstyling/core";',
    "",
    "type SuperstylingConfig = typeof defaultSystem.config;",
    "",
    'declare module "tamagui" {',
    "  // biome-ignore lint/suspicious/noEmptyInterface: augmentation target",
    "  interface TamaguiCustomConfig extends SuperstylingConfig {}",
    "}",
  ].join("\n");
}

function buildUserSystemBody(systemImport: string, exportName: string): string {
  const importSpec =
    exportName === "default"
      ? `import type system from "${systemImport}";`
      : `import type { ${exportName} } from "${systemImport}";`;
  return [
    importSpec,
    "",
    `type SuperstylingConfig = typeof ${exportName === "default" ? "system" : exportName}.config;`,
    "",
    'declare module "tamagui" {',
    "  // biome-ignore lint/suspicious/noEmptyInterface: augmentation target",
    "  interface TamaguiCustomConfig extends SuperstylingConfig {}",
    "}",
  ].join("\n");
}

/**
 * Candidate relative paths where a user's system file commonly lives. The CLI
 * tries these in order; the first that exists wins.
 */
export const SYSTEM_FILE_CANDIDATES = [
  "./superstyling.config.ts",
  "./superstyling.config.tsx",
  "./system.ts",
  "./system.tsx",
  "./src/system.ts",
  "./src/system.tsx",
  "./app/system.ts",
  "./app/system.tsx",
  "./app/superstyling.ts",
];
