import { describe, expect, test } from "vitest";
import { generateTypeDeclaration, SYSTEM_FILE_CANDIDATES } from "./generate";

describe("generateTypeDeclaration — default path", () => {
  test("imports from @superstyling/core when no systemImport is given", () => {
    const out = generateTypeDeclaration();
    expect(out).toContain('import type { defaultSystem } from "@superstyling/core"');
    expect(out).toContain("type SuperstylingConfig = typeof defaultSystem.config");
  });

  test("emits the Tamagui module-augmentation block", () => {
    const out = generateTypeDeclaration();
    expect(out).toContain('declare module "tamagui"');
    expect(out).toContain("interface TamaguiCustomConfig extends SuperstylingConfig");
  });

  test("starts with a do-not-edit header", () => {
    const out = generateTypeDeclaration();
    expect(out).toContain("Auto-generated by `superstyling init-types`");
    expect(out).toContain("Do not edit by hand");
  });

  test("ends with a trailing newline", () => {
    const out = generateTypeDeclaration();
    expect(out.endsWith("\n")).toBe(true);
  });
});

describe("generateTypeDeclaration — user system path", () => {
  test("imports the given export name from the systemImport path", () => {
    const out = generateTypeDeclaration({
      systemImport: "./superstyling.config",
      systemExportName: "system",
    });
    expect(out).toContain('import type { system } from "./superstyling.config"');
    expect(out).toContain("type SuperstylingConfig = typeof system.config");
  });

  test("supports a custom export name", () => {
    const out = generateTypeDeclaration({
      systemImport: "./lib/theme",
      systemExportName: "appSystem",
    });
    expect(out).toContain('import type { appSystem } from "./lib/theme"');
    expect(out).toContain("type SuperstylingConfig = typeof appSystem.config");
  });

  test("supports a default export", () => {
    const out = generateTypeDeclaration({
      systemImport: "./system",
      systemExportName: "default",
    });
    expect(out).toContain('import type system from "./system"');
    expect(out).toContain("type SuperstylingConfig = typeof system.config");
  });
});

describe("SYSTEM_FILE_CANDIDATES", () => {
  test("includes common conventional paths", () => {
    expect(SYSTEM_FILE_CANDIDATES).toContain("./superstyling.config.ts");
    expect(SYSTEM_FILE_CANDIDATES).toContain("./system.ts");
    expect(SYSTEM_FILE_CANDIDATES).toContain("./src/system.ts");
  });

  test("prioritizes conventional config names over loose system files", () => {
    const configIdx = SYSTEM_FILE_CANDIDATES.indexOf("./superstyling.config.ts");
    const systemIdx = SYSTEM_FILE_CANDIDATES.indexOf("./system.ts");
    expect(configIdx).toBeLessThan(systemIdx);
  });
});
