export { SuperStylingProvider, type SuperStylingProviderProps } from "./SuperStylingProvider";
export { createSystem, defaultSystem, type System } from "./createSystem";

// Style engine
export { chakraShortcuts, type ChakraShortcutMap, type ChakraShortcutName } from "./shortcuts";
export {
  pseudoPropMap,
  crossPlatformPseudoPropMap,
  webOnlyPseudoPropMap,
  ariaStatePseudoPropMap,
  type PseudoPropName,
} from "./pseudoProps";
export { translateProps, type TranslateOptions } from "./translateProps";

// Color mode
export {
  ColorModeProvider,
  useColorMode,
  useColorModeValue,
  ColorModeScript,
  buildColorModeScript,
  createWebStorage,
  DEFAULT_STORAGE_KEY,
  type ColorModeProviderProps,
  type ColorModeScriptProps,
  type ColorMode,
  type ColorModeContextValue,
  type ColorModeStorage,
  type SystemSchemeWatcher,
} from "./colorMode";

// Theme API
export {
  defaultTheme,
  mergeTheme,
  adaptChakraTheme,
  defineStyleConfig,
  defineMultiStyleConfig,
  resolveTheme,
  buildColorTokens,
  buildThemes,
  buildColorSchemeThemes,
  buildMediaQueries,
  resolveColorReference,
  type Theme,
  type ThemeInput,
  type ThemeColors,
  type ThemeSpace,
  type ThemeSizes,
  type ThemeFonts,
  type ThemeFontSizes,
  type ThemeFontWeights,
  type ThemeLineHeights,
  type ThemeLetterSpacings,
  type ThemeRadii,
  type ThemeShadows,
  type ThemeZIndices,
  type ThemeBreakpoints,
  type ThemeSemanticTokens,
  type ThemeConfig,
  type ColorScale,
  type AlphaScale,
  type SemanticTokenValue,
  type InitialColorMode,
  type SuperStylingCustomTheme,
  type ResolvedTamaguiInput,
  type SpaceKey,
  type ChakraThemeLike,
  type AdaptChakraThemeResult,
  type AdaptChakraThemeOptions,
  type MultiStyleConfigInput,
} from "./theme";

// Primitives (P2.5 + P3.1 + P3.2)
export {
  Box,
  Stack,
  HStack,
  VStack,
  Text,
  Heading,
  Divider,
  Spinner,
  Badge,
  Avatar,
  Button,
  IconButton,
  Link,
  Alert,
  Modal,
  FormControl,
  useFormControl,
  useFormControlProps,
  Input,
  Textarea,
  Checkbox,
  Switch,
  Radio,
  RadioGroup,
  Select,
  type BoxProps,
  type StackProps,
  type StackDirection,
  type TextProps,
  type HeadingProps,
  type HeadingLevel,
  type DividerProps,
  type SpinnerProps,
  type BadgeProps,
  type BadgeVariant,
  type BadgeSize,
  type AvatarProps,
  type AvatarImageProps,
  type AvatarFallbackProps,
  type ButtonProps,
  type ButtonVariant,
  type ButtonSize,
  type IconButtonProps,
  type LinkProps,
  type AlertProps,
  type AlertStatus,
  type AlertVariant,
  type ModalProps,
  type ModalSize,
  type ModalMotionPreset,
  type ModalScrollBehavior,
  type ModalOverlayProps,
  type ModalContentProps,
  type FormControlRootProps,
  type FormControlContextValue,
  type InputAriaProps,
  type InputProps,
  type InputVariant,
  type InputSize,
  type InputElement,
  type TextareaProps,
  type TextareaElement,
  type CheckboxProps,
  type CheckboxSize,
  type CheckboxElement,
  type SwitchProps,
  type SwitchSize,
  type SwitchElement,
  type RadioProps,
  type RadioGroupProps,
  type RadioSize,
  type RadioElement,
  type RadioGroupElement,
  type SelectProps,
  type SelectOptionProps,
  type SelectSize,
  type SelectElement,
  // Phase 10 — layout primitives
  Flex,
  Center,
  Container,
  Spacer,
  AspectRatio,
  Grid,
  GridItem,
  SimpleGrid,
  Wrap,
  WrapItem,
  Code,
  Kbd,
  Tag,
  Image,
  List,
  OrderedList,
  UnorderedList,
  ListItem,
  ListIcon,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  InputLeftAddon,
  InputRightAddon,
  ButtonGroup,
  CheckboxGroup,
  useCheckboxGroup,
  CloseButton,
  type FlexProps,
  type FlexDirection,
  type FlexJustify,
  type FlexAlign,
  type FlexWrap,
  type FlexElement,
  type CenterProps,
  type ContainerProps,
  type ContainerElement,
  type SpacerProps,
  type SpacerElement,
  type AspectRatioProps,
  type GridProps,
  type GridItemProps,
  type GridElement,
  type SimpleGridProps,
  type WrapProps,
  type WrapItemProps,
  type WrapElement,
  type CodeProps,
  type CodeElement,
  type KbdProps,
  type KbdElement,
  type TagProps,
  type TagVariant,
  type TagSize,
  type TagElement,
  type TagLabelProps,
  type TagCloseButtonProps,
  type TagIconSlotProps,
  type ImageProps,
  type ImageObjectFit,
  type ImageElement,
  type ListProps,
  type ListItemProps,
  type ListIconProps,
  type ListElement,
  type InputGroupProps,
  type InputElementProps,
  type InputAddonProps,
  type InputGroupElement,
  type ButtonGroupProps,
  type CheckboxGroupProps,
  type CheckboxGroupContextValue,
  type CloseButtonProps,
  // Phase 11 — overlays
  Drawer,
  Tooltip,
  Popover,
  Menu,
  AlertDialog,
  type DrawerProps,
  type DrawerPlacement,
  type DrawerSize,
  type DrawerOverlayProps,
  type DrawerContentProps,
  type TooltipProps,
  type TooltipPlacement,
  type PopoverProps,
  type PopoverPlacement,
  type MenuProps,
  type MenuItemProps,
  type MenuOptionGroupProps,
  type MenuItemOptionProps,
  type AlertDialogProps,
  // Phase 12 — navigation & disclosure
  Tabs,
  Accordion,
  Breadcrumb,
  BreadcrumbChevron,
  Stepper,
  useSteps,
  Fade,
  ScaleFade,
  Slide,
  Collapse,
  type TabsProps,
  type TabsVariant,
  type TabsOrientation,
  type TabsTabProps,
  type AccordionProps,
  type AccordionItemProps,
  type BreadcrumbProps,
  type BreadcrumbItemProps,
  type StepperProps,
  type StepStatus,
  type StepperOrientation,
  type TransitionBaseProps,
  type ScaleFadeProps,
  type SlideProps,
  type SlideDirection,
  type CollapseProps,
  // Phase 13 — data & forms + real native
  Table,
  TableContainer,
  NumberInput,
  PinInput,
  Slider,
  RangeSlider,
  Progress,
  CircularProgress,
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Stat,
  Editable,
  useEditableControls,
  type TableProps,
  type TableVariant,
  type TableSize,
  type CellProps,
  type NumberInputProps,
  type PinInputProps,
  type SliderProps,
  type ProgressProps,
  type ProgressSize,
  type CircularProgressProps,
  type SkeletonProps,
  type SkeletonCircleProps,
  type SkeletonTextProps,
  type StatProps,
  type StatArrowType,
  type StatArrowProps,
  type EditableProps,
} from "./components";

// Toast — default cross-platform + opt-in native-feel variant
export {
  useToast,
  useNativeToast,
  type ToastOptions,
  type ToastStatus,
  type ToastPosition,
} from "./toast";

// Breakpoint context (for custom components that want theme-aware responsive parsing)
export { BreakpointProvider, useBreakpointNames } from "./system/BreakpointContext";

// Phase 14 — Chakra-parity hooks
export {
  useDisclosure,
  useBoolean,
  useControllableState,
  useMergeRefs,
  useMediaQuery,
  useBreakpointValue,
  useClipboard,
  useTheme,
  useToken,
  useOutsideClick,
  type UseDisclosureProps,
  type UseDisclosureReturn,
  type UseBooleanControls,
  type UseControllableStateProps,
  type BreakpointValueMap,
  type UseClipboardOptions,
  type UseClipboardReturn,
  type ThemeScale,
  type UseOutsideClickProps,
} from "./hooks";

// Overlay registry
export {
  OverlayRegistryProvider,
  useOverlayRegistry,
  type OverlayRegistryProviderProps,
  type OverlayRegistryAPI,
  type RegisteredOverlay,
} from "./overlay";

// Direct Tamagui re-exports retained for users who want the unwrapped primitives.
export { XStack, YStack, H1, H2, H3, H4, H5, H6 } from "tamagui";
