export { SuperStylingProvider, type SuperStylingProviderProps } from "./SuperStylingProvider";
export { createSystem, defaultSystem, type System } from "./createSystem";

// Style engine
export { chakraShortcuts, type ChakraShortcutMap, type ChakraShortcutName } from "./shortcuts";
export {
  pseudoPropMap,
  crossPlatformPseudoPropMap,
  webOnlyPseudoPropMap,
  ariaStatePseudoPropMap,
  type PseudoPropName,
} from "./pseudoProps";
export { translateProps, type TranslateOptions } from "./translateProps";

// Color mode
export {
  ColorModeProvider,
  useColorMode,
  useColorModeValue,
  ColorModeScript,
  buildColorModeScript,
  createWebStorage,
  DEFAULT_STORAGE_KEY,
  type ColorModeProviderProps,
  type ColorModeScriptProps,
  type ColorMode,
  type ColorModeContextValue,
  type ColorModeStorage,
  type SystemSchemeWatcher,
} from "./colorMode";

// Theme API
export {
  defaultTheme,
  mergeTheme,
  resolveTheme,
  buildColorTokens,
  buildThemes,
  buildColorSchemeThemes,
  buildMediaQueries,
  resolveColorReference,
  type Theme,
  type ThemeInput,
  type ThemeColors,
  type ThemeSpace,
  type ThemeSizes,
  type ThemeFonts,
  type ThemeFontSizes,
  type ThemeFontWeights,
  type ThemeLineHeights,
  type ThemeLetterSpacings,
  type ThemeRadii,
  type ThemeShadows,
  type ThemeZIndices,
  type ThemeBreakpoints,
  type ThemeSemanticTokens,
  type ThemeConfig,
  type ColorScale,
  type AlphaScale,
  type SemanticTokenValue,
  type InitialColorMode,
  type SuperStylingCustomTheme,
  type ResolvedTamaguiInput,
  type SpaceKey,
} from "./theme";

// Primitives (P2.5 + P3.1 + P3.2)
export {
  Box,
  Stack,
  HStack,
  VStack,
  Text,
  Heading,
  Divider,
  Spinner,
  Badge,
  Avatar,
  Button,
  IconButton,
  Link,
  Alert,
  Modal,
  FormControl,
  useFormControl,
  useFormControlProps,
  Input,
  Textarea,
  Checkbox,
  Switch,
  Radio,
  RadioGroup,
  Select,
  type BoxProps,
  type StackProps,
  type StackDirection,
  type TextProps,
  type HeadingProps,
  type HeadingLevel,
  type DividerProps,
  type SpinnerProps,
  type BadgeProps,
  type BadgeVariant,
  type BadgeSize,
  type AvatarProps,
  type AvatarImageProps,
  type AvatarFallbackProps,
  type ButtonProps,
  type ButtonVariant,
  type ButtonSize,
  type IconButtonProps,
  type LinkProps,
  type AlertProps,
  type AlertStatus,
  type AlertVariant,
  type ModalProps,
  type ModalSize,
  type ModalMotionPreset,
  type ModalScrollBehavior,
  type ModalOverlayProps,
  type ModalContentProps,
  type FormControlRootProps,
  type FormControlContextValue,
  type InputAriaProps,
  type InputProps,
  type InputVariant,
  type InputSize,
  type InputElement,
  type TextareaProps,
  type TextareaElement,
  type CheckboxProps,
  type CheckboxSize,
  type CheckboxElement,
  type SwitchProps,
  type SwitchSize,
  type SwitchElement,
  type RadioProps,
  type RadioGroupProps,
  type RadioSize,
  type RadioElement,
  type RadioGroupElement,
  type SelectProps,
  type SelectOptionProps,
  type SelectSize,
  type SelectElement,
  // Phase 10 — layout primitives
  Flex,
  Center,
  Container,
  Spacer,
  AspectRatio,
  Grid,
  GridItem,
  SimpleGrid,
  Wrap,
  WrapItem,
  Code,
  Kbd,
  Tag,
  Image,
  List,
  OrderedList,
  UnorderedList,
  ListItem,
  ListIcon,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  InputLeftAddon,
  InputRightAddon,
  ButtonGroup,
  CheckboxGroup,
  useCheckboxGroup,
  CloseButton,
  type FlexProps,
  type FlexDirection,
  type FlexJustify,
  type FlexAlign,
  type FlexWrap,
  type FlexElement,
  type CenterProps,
  type ContainerProps,
  type ContainerElement,
  type SpacerProps,
  type SpacerElement,
  type AspectRatioProps,
  type GridProps,
  type GridItemProps,
  type GridElement,
  type SimpleGridProps,
  type WrapProps,
  type WrapItemProps,
  type WrapElement,
  type CodeProps,
  type CodeElement,
  type KbdProps,
  type KbdElement,
  type TagProps,
  type TagVariant,
  type TagSize,
  type TagElement,
  type TagLabelProps,
  type TagCloseButtonProps,
  type TagIconSlotProps,
  type ImageProps,
  type ImageObjectFit,
  type ImageElement,
  type ListProps,
  type ListItemProps,
  type ListIconProps,
  type ListElement,
  type InputGroupProps,
  type InputElementProps,
  type InputAddonProps,
  type InputGroupElement,
  type ButtonGroupProps,
  type CheckboxGroupProps,
  type CheckboxGroupContextValue,
  type CloseButtonProps,
} from "./components";

// Breakpoint context (for custom components that want theme-aware responsive parsing)
export { BreakpointProvider, useBreakpointNames } from "./system/BreakpointContext";

// Overlay registry
export {
  OverlayRegistryProvider,
  useOverlayRegistry,
  type OverlayRegistryProviderProps,
  type OverlayRegistryAPI,
  type RegisteredOverlay,
} from "./overlay";

// Direct Tamagui re-exports retained for users who want the unwrapped primitives.
export { XStack, YStack, H1, H2, H3, H4, H5, H6 } from "tamagui";
