#!/usr/bin/env node
/**
 * `superstyling` CLI entry.
 *
 * Usage:
 *   superstyling init-types [--system=<path>] [--export=<name>] [--output=<path>]
 *   superstyling --help
 *
 * Generates a `superstyling.d.ts` file that augments Tamagui's TypeScript
 * config with your system's type info (PLAN.md Q18 / P2.6). Run once after
 * setup, and again any time your theme shape changes enough to affect types.
 *
 * This file is intentionally dependency-free ESM — no `src/` imports — so it
 * runs directly from the published package without a build step. The same
 * generation logic lives in `src/cli/generate.ts` for tests and programmatic
 * use; keep the two in sync.
 */
import { writeFileSync, existsSync } from "node:fs";
import { resolve, basename } from "node:path";
import { parseArgs } from "node:util";

// Keep in sync with `src/cli/generate.ts`.
const SYSTEM_FILE_CANDIDATES = [
  "./superstyling.config.ts",
  "./superstyling.config.tsx",
  "./system.ts",
  "./system.tsx",
  "./src/system.ts",
  "./src/system.tsx",
  "./app/system.ts",
  "./app/system.tsx",
  "./app/superstyling.ts",
];

function generateTypeDeclaration({ systemImport, systemExportName = "system" } = {}) {
  const header = [
    "// Auto-generated by `superstyling init-types`.",
    "// Do not edit by hand — rerun the CLI after changing your system config.",
    "//",
    "// This file teaches Tamagui's TypeScript types about your Superstyling",
    '// system so that style props (e.g., `bg="blue.500"`), shortcuts,',
    "// semantic tokens, and colorScheme themes autocomplete correctly.",
  ].join("\n");
  const body = systemImport
    ? buildUserSystemBody(systemImport, systemExportName)
    : buildDefaultSystemBody();
  return `${header}\n${body}\n`;
}

function buildDefaultSystemBody() {
  return [
    'import type { defaultSystem } from "@superstyling/core";',
    "",
    "type SuperstylingConfig = typeof defaultSystem.config;",
    "",
    'declare module "tamagui" {',
    "  // biome-ignore lint/suspicious/noEmptyInterface: augmentation target",
    "  interface TamaguiCustomConfig extends SuperstylingConfig {}",
    "}",
  ].join("\n");
}

function buildUserSystemBody(systemImport, exportName) {
  const importSpec =
    exportName === "default"
      ? `import type system from "${systemImport}";`
      : `import type { ${exportName} } from "${systemImport}";`;
  const typeRef = exportName === "default" ? "system" : exportName;
  return [
    importSpec,
    "",
    `type SuperstylingConfig = typeof ${typeRef}.config;`,
    "",
    'declare module "tamagui" {',
    "  // biome-ignore lint/suspicious/noEmptyInterface: augmentation target",
    "  interface TamaguiCustomConfig extends SuperstylingConfig {}",
    "}",
  ].join("\n");
}

const HELP = `superstyling — Superstyling CLI

Usage:
  superstyling init-types [options]

Commands:
  init-types          Generate superstyling.d.ts for Tamagui type augmentation.

Options:
  --system=<path>     Import path to your system file (e.g., "./superstyling.config").
                      If omitted, the CLI checks conventional paths; falling back
                      to @superstyling/core's defaultSystem if none are found.
  --export=<name>     Name of the exported system symbol. Default: "system".
                      Use "default" for a default export.
  --output=<path>     Where to write the .d.ts file. Default: "./superstyling.d.ts".
  --force             Overwrite an existing output file without prompting.
  --help, -h          Show this help and exit.
`;

function main() {
  const parsed = parseCliArgs(process.argv.slice(2));
  if (parsed.help || parsed.command === undefined) {
    process.stdout.write(HELP);
    process.exit(parsed.help ? 0 : 1);
  }
  if (parsed.command !== "init-types") {
    process.stderr.write(`Unknown command: ${parsed.command}\n\n${HELP}`);
    process.exit(1);
  }

  const outputPath = resolve(process.cwd(), parsed.output);
  if (existsSync(outputPath) && !parsed.force) {
    process.stderr.write(`${basename(outputPath)} already exists. Use --force to overwrite.\n`);
    process.exit(1);
  }

  const systemImport = parsed.system ?? detectSystemFile();
  const content = generateTypeDeclaration({
    systemImport,
    systemExportName: parsed.exportName,
  });

  writeFileSync(outputPath, content, "utf8");
  process.stdout.write(
    `wrote ${outputPath}\n` +
      (systemImport
        ? `  augmenting from: ${systemImport}\n`
        : `  augmenting from: @superstyling/core (defaultSystem)\n`),
  );
}

function parseCliArgs(argv) {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      system: { type: "string" },
      export: { type: "string", default: "system" },
      output: { type: "string", default: "./superstyling.d.ts" },
      force: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false },
    },
  });
  return {
    command: positionals[0],
    system: values.system,
    exportName: values.export,
    output: values.output,
    force: values.force,
    help: values.help,
  };
}

function detectSystemFile() {
  for (const candidate of SYSTEM_FILE_CANDIDATES) {
    if (existsSync(resolve(process.cwd(), candidate))) {
      // Strip the extension; TypeScript import paths don't include .ts / .tsx.
      return candidate.replace(/\.(ts|tsx)$/, "");
    }
  }
  return undefined;
}

main();
